stages:
 - build
 - package

variables:
  DEPS: build-essential git

.tags: &tags
  tags:
    - librem5

before_script:
 - apt-get -y update
 - apt-get -y install $DEPS
 - DEB_BUILD_PROFILES=pkg.phoc.embedwlroots apt-get -y build-dep .

build-with-xwayland:
  stage: build
  <<: *tags
  script:
    - export LC_ALL=C.UTF-8
    - git submodule update --init
    - meson . _build -Dxwayland=enabled
    - ninja -C _build
    - ninja -C _build install

build-without-xwayland:
  stage: build
  <<: *tags
  script:
    - export LC_ALL=C.UTF-8
    - git submodule update --init
    - meson . _build -Dxwayland=disabled
    - ninja -C _build
    - ninja -C _build install

package-deb-with-wlroots:
  <<: *tags
  stage: package
  script:
    - git submodule update --init
    - DEB_BUILD_PROFILES=pkg.phoc.embedwlroots dpkg-buildpackage -uc -us
    # Must not be dynamically linked against wlroots
    - ldd debian/phoc/usr/bin/phoc | grep -qs libwlroots && exit 1 || true
    - cp ../*.deb .
  artifacts:
    paths:
      - "*.deb"

package-deb-without-wlroots:
  <<: *tags
  stage: package
  before_script:
    - echo "deb http://deb.debian.org/debian/ experimental main" > /etc/apt/sources.list.d/experimental.list
    - apt-get -y update
    - apt-get -y install $DEPS
    # This pulls in wlroots build-deps and so avoids pulling in e.g. mesa from
    # experimental due to  pulling wlroots from experimental
    # Once we have wlroots in our archive we can drop the build profile
    - DEB_BUILD_PROFILES=pkg.phoc.embedwlroots apt-get -y build-dep .
    - apt-get -y -t experimental install libwlroots-dev
  script:
    - dpkg-buildpackage -uc -us
    # Must be dynamically linked against wlroots
    - ldd debian/phoc/usr/bin/phoc | grep -qs libwlroots
    - cp ../*.deb .
  artifacts:
    paths:
      - "*.deb"
